# -*- coding: utf-8 -*-
"""(BFS) 최소 경로로 탈출 하기.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fqC--GHFER48KVSWvSUKRK2k-bpbL1Ud
"""

from collections import deque

n, m = tuple(map(int, input().split()))
grid = [list(map(int, input().split())) for _ in range(n)]
visited = [[False for _ in range(m)] for _ in range(n)]

print(grid)

q = deque()

def push(x,y,s):
    grid[x][y] = s
    visited[x][y] = True
    q.append((x,y))

def can_go(x,y):
    if not (0<=x<n and 0<= y<m):
        return False
    if visited[x][y]:
        return False
    if grid[x][y] == 0:
        return False
    return True

def BFS():
    dx, dy = [-1,1,0,0], [0,0,-1,1]
    while q:
        x,y = q.popleft()
        for i,j in zip(dx, dy):
            nx, ny = x+i, y+j

            if can_go(nx,ny):
                push(nx,ny, grid[x][y]+1)

push(0,0,1)
BFS()
if grid[n-1][m-1] -1 != 0:
  print(grid[n-1][m-1] -1)
else:
  print(-1)

